spring:
  application:
    name: eureka-server
server:
  port: 8001

eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/
  server:
    enable-self-preservation: false