spring:
  application:
    name: eureka-server
server:
  port: 8000

eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://peer2:8001/eureka/
  server:
    enable-self-preservation: false