server:
  port: 9000

spring:
  application:
    name: client

eureka:
  instance:
    namespace: client
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/, http://peer2:8001/eureka/